name: Workflow of Solar System

on:
    push:
        branches:
            - main
            - 'feature/**'
    workflow_dispatch:

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
    unit-testing:
        name: Unit Testing
        strategy:
            matrix:
                nodejs_version: [18, 19, 20]
                os: [ubuntu-latest, macos-latest]
                exclude:
                    - nodejs_version: 18
                      os: macos-latest
        runs-on: ${{ matrix.os }}
        steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: install nodejs
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.nodejs_version }}
        
        - name: install dependencies
          run: npm install

        - name: unit test
          run: npm test

        - name: archive test result
          uses: actions/upload-artifact@v3
          with:
            name: test-result
            path: test-results.xml
    
    code-coverage:
        name: Code coverage
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: install nodejs
          uses: actions/setup-node@v3
          with:
            node-version: 18
        
        - name: install dependencies
          run: npm install

        - name: code coverage
          run: npm run coverage

        - name: archive coverage result
          uses: actions/upload-artifact@v3
          with:
            name: coverage-result
            path: coverage
            retention-day: 5
